/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import logica.GestorBitacora;
/**
 *
 * @author vicky
 */
public class Registrar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registrar.class.getName());

    /**
     * Creates new form Registro
     */
    public Registrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtNombre = new javax.swing.JTextField();
        jTxtEspecie = new javax.swing.JTextField();
        jTxtEdad = new javax.swing.JTextField();
        jTxtSalud = new javax.swing.JTextField();
        jBGuardar = new javax.swing.JButton();
        jBRegresar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTxtCodigo = new javax.swing.JTextField();
        jTxtEstado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 153));
        jLabel1.setText("Gestion de Animales - Registrar Animal");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jLabel2.setText("Nombre :");

        jLabel3.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jLabel3.setText("Especie :");

        jLabel4.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jLabel4.setText("Edad :");

        jLabel5.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jLabel5.setText("Estado de Salud :");

        jTxtNombre.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N

        jTxtEspecie.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N

        jTxtEdad.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N

        jTxtSalud.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N

        jBGuardar.setBackground(new java.awt.Color(255, 0, 153));
        jBGuardar.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jBGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(this::jBGuardarActionPerformed);

        jBRegresar.setBackground(new java.awt.Color(255, 0, 153));
        jBRegresar.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jBRegresar.setForeground(new java.awt.Color(255, 255, 255));
        jBRegresar.setText("Regresar");
        jBRegresar.addActionListener(this::jBRegresarActionPerformed);

        jLabel6.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jLabel6.setText("Código(AN-001) :");

        jLabel7.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jLabel7.setText("Estado :");

        jTxtCodigo.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N

        jTxtEstado.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTxtNombre)
                                    .addComponent(jTxtEdad)
                                    .addComponent(jTxtEspecie)
                                    .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jTxtSalud)
                            .addComponent(jTxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel4)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel5)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jTxtEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jTxtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jTxtSalud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jTxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGuardar)
                    .addComponent(jBRegresar))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
                                  
    String codigo = jTxtCodigo.getText().trim();
    String nombre = jTxtNombre.getText().trim();
    String especie = jTxtEspecie.getText().trim();
    String edadStr = jTxtEdad.getText().trim();
    String salud = jTxtSalud.getText().trim();
    String estado = jTxtEstado.getText().trim();

    // 1. Validar campos vacíos
    if (codigo.isEmpty() || nombre.isEmpty() || especie.isEmpty() || edadStr.isEmpty() || salud.isEmpty() || estado.isEmpty()) {
       javax.swing.JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2. Validar prefijo del código del animal
    if (!codigo.startsWith("AN-") && !codigo.startsWith("A-")) {
        javax.swing.JOptionPane.showMessageDialog(this, "El código del animal debe iniciar con 'AN-' o 'A-' (Ej: AN-001).", "Error de formato", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 3. Validar que la edad sea un número válido y esté entre 0 y 25
    try {
        int edad = Integer.parseInt(edadStr);
        if (edad < 0 || edad > 25) {
            javax.swing.JOptionPane.showMessageDialog(this, "La edad debe estar en un rango de 0 a 25 años.", "Error de validación", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "La edad debe ser un número entero válido.", "Error de formato", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 4. Validar capacidad máxima de la matriz (100 animales)
    if (logica.GestorDatos.contadorAnimales >= 100) {
        javax.swing.JOptionPane.showMessageDialog(this, "Se ha alcanzado la capacidad máxima de animales permitida (100).", "Capacidad llena", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 5. Guardar en la matriz estática de GestorDatos (5 columnas)
    int index = logica.GestorDatos.contadorAnimales;
    logica.GestorDatos.animales[index][0] = codigo;
    logica.GestorDatos.animales[index][1] = especie; // O puedes guardar el nombre combinando nombre y especie
    logica.GestorDatos.animales[index][2] = edadStr;
    logica.GestorDatos.animales[index][3] = salud;
    logica.GestorDatos.animales[index][4] = estado;

    // 6. Incrementar contador global
    logica.GestorDatos.contadorAnimales++;

    // Mensaje de éxito
    javax.swing.JOptionPane.showMessageDialog(this, "¡Animal registrado y guardado exitosamente!");

    // 7. Limpiar campos
    jTxtCodigo.setText("");
    jTxtNombre.setText("");
    jTxtEspecie.setText("");
    jTxtEdad.setText("");
    jTxtSalud.setText("");
    jTxtEstado.setText("");
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegresarActionPerformed
       GestorBitacora.registrarAccion("admin1", "ANIMALES", "ALTA", "Animal A-014 registrado");
    VentanaPrincipal menuPrincipal = new VentanaPrincipal();
    menuPrincipal.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jBRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Registrar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtEdad;
    private javax.swing.JTextField jTxtEspecie;
    private javax.swing.JTextField jTxtEstado;
    private javax.swing.JTextField jTxtNombre;
    private javax.swing.JTextField jTxtSalud;
    // End of variables declaration//GEN-END:variables
}
