/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import logica.GestorDatos;

/**
 *
 * @author vicky
 */
public class RegistrarAdoptante extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistrarAdoptante.class.getName());

    /**
     * Creates new form RegistrarAdoptante
     */
    public RegistrarAdoptante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTtxtCodigo = new javax.swing.JTextField();
        jTtxtNombre = new javax.swing.JTextField();
        jTtxtDpi = new javax.swing.JTextField();
        jTtxtTelefono = new javax.swing.JTextField();
        jBGuardar = new javax.swing.JButton();
        jBRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 153));
        jLabel1.setText("Registrar Adoptante");

        jLabel2.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jLabel2.setText("Código (AD-001) :");

        jLabel3.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jLabel3.setText("Nombre Completo :");

        jLabel4.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jLabel4.setText("DPI (13 digitos):");

        jLabel5.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jLabel5.setText("Teléfono (8 digitos) :");

        jTtxtCodigo.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N

        jTtxtNombre.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N

        jTtxtDpi.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N

        jTtxtTelefono.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N

        jBGuardar.setBackground(new java.awt.Color(255, 0, 153));
        jBGuardar.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jBGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(this::jBGuardarActionPerformed);

        jBRegresar.setBackground(new java.awt.Color(255, 0, 153));
        jBRegresar.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jBRegresar.setForeground(new java.awt.Color(255, 255, 255));
        jBRegresar.setText("Regresar");
        jBRegresar.addActionListener(this::jBRegresarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jBRegresar))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTtxtCodigo)
                    .addComponent(jTtxtNombre)
                    .addComponent(jTtxtDpi)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBGuardar)
                        .addGap(0, 70, Short.MAX_VALUE))
                    .addComponent(jTtxtTelefono))
                .addGap(42, 42, 42))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel3)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel4)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTtxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jTtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jTtxtDpi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jTtxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGuardar)
                    .addComponent(jBRegresar))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
                                 
    String codigo = jTtxtCodigo.getText().trim();
    String nombre = jTtxtNombre.getText().trim();
    String dpi = jTtxtDpi.getText().trim();
    String telefono = jTtxtTelefono.getText().trim();

    // 1. Validar que no haya campos vacíos
    if (codigo.isEmpty() || nombre.isEmpty() || dpi.isEmpty() || telefono.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    // 2. Validar que el código inicie con el prefijo "AD-"
    if (!codigo.startsWith("AD-")) {
        javax.swing.JOptionPane.showMessageDialog(this, "El código del adoptante debe iniciar con el prefijo 'AD-' (Ej: AD-001).", "Error de formato", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }
    // 3. Validar que el DPI tenga exactamente 13 dígitos numéricos
    if (dpi.length() != 13 || !dpi.matches("\\d+")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: El DPI debe contener exactamente 13 dígitos numéricos.", "Error de validación", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }
    // 4. Validar que el Teléfono tenga exactamente 8 dígitos numéricos
    if (telefono.length() != 8 || !telefono.matches("\\d+")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: El teléfono debe contener exactamente 8 dígitos numéricos.", "Error de validación", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }
    // 5. Validar la capacidad máxima de la matriz estática (100 adoptantes)
    if (logica.GestorDatos.contadorAdoptantes >= 100) {
        javax.swing.JOptionPane.showMessageDialog(this, "Se ha alcanzado la capacidad máxima de adoptantes permitida (100).", "Capacidad llena", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }
    // 6. Guardar los datos en la matriz estática de GestorDatos
    int index = logica.GestorDatos.contadorAdoptantes;
    logica.GestorDatos.adoptantes[index][0] = codigo;
    logica.GestorDatos.adoptantes[index][1] = nombre;
    logica.GestorDatos.adoptantes[index][2] = dpi;
    logica.GestorDatos.adoptantes[index][3] = telefono;
    logica.GestorDatos.contadorAdoptantes++;
    javax.swing.JOptionPane.showMessageDialog(this, "¡Adoptante registrado y guardado exitosamente!");
    // 8. Limpiar 
    jTtxtCodigo.setText("");
    jTtxtNombre.setText("");
    jTtxtDpi.setText("");
    jTtxtTelefono.setText("");
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegresarActionPerformed
        this.dispose(); // Cierra la ventana actual
    }//GEN-LAST:event_jBRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistrarAdoptante().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTtxtCodigo;
    private javax.swing.JTextField jTtxtDpi;
    private javax.swing.JTextField jTtxtNombre;
    private javax.swing.JTextField jTtxtTelefono;
    // End of variables declaration//GEN-END:variables
}
