/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import logica.GestorDatos;
import logica.GestorBitacora;
/**
 *
 * @author vicky
 */
public class RegistrarEspacio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistrarEspacio.class.getName());

    /**
     * Creates new form RegistrarEspacio
     */
    public RegistrarEspacio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jBRegresar = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jTtxtCodigo = new javax.swing.JTextField();
        jTtxtArea = new javax.swing.JTextField();
        jTtxtEstado = new javax.swing.JTextField();
        jTtxtCodigoAnimal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 153));
        jLabel1.setText("Espacio de Refugio");

        jLabel2.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jLabel2.setText("Código Espacio (ESP-001) :");

        jLabel3.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jLabel3.setText("Área (Perros) :");

        jLabel4.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jLabel4.setText("Estado (Disponible/Ocupado) :");

        jLabel5.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jLabel5.setText("Código Animal (AN-001):");

        jBRegresar.setBackground(new java.awt.Color(255, 0, 153));
        jBRegresar.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jBRegresar.setForeground(new java.awt.Color(255, 255, 255));
        jBRegresar.setText("Regresar");
        jBRegresar.addActionListener(this::jBRegresarActionPerformed);

        jBGuardar.setBackground(new java.awt.Color(255, 0, 153));
        jBGuardar.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jBGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(this::jBGuardarActionPerformed);

        jTtxtCodigo.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jTtxtCodigo.addActionListener(this::jTtxtCodigoActionPerformed);

        jTtxtArea.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N

        jTtxtEstado.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N

        jTtxtCodigoAnimal.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTtxtCodigo)
                            .addComponent(jTtxtArea)
                            .addComponent(jTtxtEstado)
                            .addComponent(jTtxtCodigoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel1)))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBRegresar)
                .addGap(18, 18, 18)
                .addComponent(jBGuardar)
                .addGap(146, 146, 146))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTtxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jTtxtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jTtxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jTtxtCodigoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBRegresar)
                    .addComponent(jBGuardar))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
                                
                                        
    String codigoEspacio = jTtxtCodigo.getText().trim();
    String area = jTtxtArea.getText().trim();
    String estado = jTtxtEstado.getText().trim();
    String codAnimal = jTtxtCodigoAnimal.getText().trim();

    // 1. Validar campos obligatorios básicos
    if (codigoEspacio.isEmpty() || area.isEmpty() || estado.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, completa los campos principales (Código, Área y Estado).", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2. Validar prefijo del código de espacio
    if (!codigoEspacio.startsWith("ESP-") && !codigoEspacio.startsWith("E-")) {
        javax.swing.JOptionPane.showMessageDialog(this, "El código del espacio debe iniciar con 'ESP-' o 'E-' (ESP-001).", "Error de formato", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 3. Si asignan un código de animal, validar que dicho animal exista en el sistema
    if (!codAnimal.isEmpty()) {
        boolean animalExiste = false;
        for (int i = 0; i < GestorDatos.contadorAnimales; i++) {
            if (GestorDatos.animales[i][0].equals(codAnimal)) {
                animalExiste = true;
                break;
            }
        }
        if (!animalExiste) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: El código de animal ingresado no existe en el sistema.", "Animal no encontrado", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
    } else {
        codAnimal = "Ninguno"; // Valor por defecto si no se le asigna animal todavía
    }

    // 4. Validar capacidad máxima de la matriz (100 espacios)
    if (GestorDatos.contadorEspacios >= 100) {
        javax.swing.JOptionPane.showMessageDialog(this, "Se ha alcanzado la capacidad máxima de espacios de refugio.", "Capacidad llena", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 5. Guardar en la matriz estática
    int index = GestorDatos.contadorEspacios;
    GestorDatos.espacios[index][0] = codigoEspacio;
    GestorDatos.espacios[index][1] = area;
    GestorDatos.espacios[index][2] = estado;
    GestorDatos.espacios[index][3] = codAnimal;

    // 6. Incrementar contador
    GestorDatos.contadorEspacios++;

    // --- NUEVO: GUARDAR EN EL ARCHIVO refugios.txt ---
    try {
        java.io.FileWriter escritor = new java.io.FileWriter("refugios.txt", true);
        java.io.PrintWriter linea = new java.io.PrintWriter(escritor);
        linea.println("Código: " + codigoEspacio + " | Área: " + area + " | Estado: " + estado + " | Animal: " + codAnimal);
        linea.close();
        escritor.close();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Aviso: No se pudo escribir en el archivo de texto: " + e.getMessage());
    }
    // ------------------------------------------------

    javax.swing.JOptionPane.showMessageDialog(this, "Espacio de refugio registrado con éxito!");

    // 7. Limpiar campos
    jTtxtCodigo.setText("");
    jTtxtArea.setText("");
    jTtxtEstado.setText("");
    jTtxtCodigoAnimal.setText("");
    
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegresarActionPerformed
    GestorBitacora.registrarAccion("admin1", "ANIMALES", "ALTA", "Animal A-014 registrado");                                        
    VentanaPrincipal menuPrincipal = new VentanaPrincipal();
    menuPrincipal.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jBRegresarActionPerformed

    private void jTtxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTtxtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTtxtCodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistrarEspacio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTtxtArea;
    private javax.swing.JTextField jTtxtCodigo;
    private javax.swing.JTextField jTtxtCodigoAnimal;
    private javax.swing.JTextField jTtxtEstado;
    // End of variables declaration//GEN-END:variables
}
