/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author vicky
 */
public class SolicitudAdopcion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SolicitudAdopcion.class.getName());

    /**
     * Creates new form SolicitudAdopcion
     */
    public SolicitudAdopcion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTtxtCodigo = new javax.swing.JTextField();
        jTtxtCodigoAdoptante = new javax.swing.JTextField();
        jTtxtCodigoAnimal = new javax.swing.JTextField();
        jBGuardar = new javax.swing.JButton();
        jBRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 153));
        jLabel1.setText("Registrar Solicitud de Adopción");

        jLabel2.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jLabel2.setText("Código de la Solicitud (SO-001) :");

        jLabel3.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jLabel3.setText("Código del Adoptante (AD-001) :");

        jLabel4.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jLabel4.setText("Código del Animal (AN-001) :");

        jTtxtCodigo.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N

        jTtxtCodigoAdoptante.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N

        jTtxtCodigoAnimal.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jTtxtCodigoAnimal.addActionListener(this::jTtxtCodigoAnimalActionPerformed);

        jBGuardar.setBackground(new java.awt.Color(255, 0, 153));
        jBGuardar.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jBGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(this::jBGuardarActionPerformed);

        jBRegresar.setBackground(new java.awt.Color(255, 0, 153));
        jBRegresar.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jBRegresar.setForeground(new java.awt.Color(255, 255, 255));
        jBRegresar.setText("Regresar");
        jBRegresar.addActionListener(this::jBRegresarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTtxtCodigo)
                    .addComponent(jTtxtCodigoAdoptante)
                    .addComponent(jTtxtCodigoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jBRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTtxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTtxtCodigoAdoptante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTtxtCodigoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBRegresar)
                    .addComponent(jBGuardar))
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTtxtCodigoAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTtxtCodigoAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTtxtCodigoAnimalActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
                                 
    String codSolicitud = jTtxtCodigo.getText().trim();
    String codAdoptante = jTtxtCodigoAdoptante.getText().trim();
    String codAnimal = jTtxtCodigoAnimal.getText().trim();

    // 1. Validar campos vacíos
    if (codSolicitud.isEmpty() || codAdoptante.isEmpty() || codAnimal.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2. Validar prefijo de la solicitud (Ej: SO-)
    if (!codSolicitud.startsWith("SO-")) {
        javax.swing.JOptionPane.showMessageDialog(this, "El código de solicitud debe iniciar con el prefijo 'SO-' (Ej: SO-001).", "Error de formato", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 3. Validar que el Adoptante exista en el sistema
    boolean adoptanteExiste = false;
    for (int i = 0; i < logica.GestorDatos.contadorAdoptantes; i++) {
        if (logica.GestorDatos.adoptantes[i][0].equals(codAdoptante)) {
            adoptanteExiste = true;
            break;
        }
    }
    if (!adoptanteExiste) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: El código de adoptante ingresado no existe.", "Adoptante no encontrado", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 4. Validar que el Animal exista en el sistema
    boolean animalExiste = false;
    for (int i = 0; i < logica.GestorDatos.contadorAnimales; i++) {
        if (logica.GestorDatos.animales[i][0].equals(codAnimal)) {
            animalExiste = true;
            break;
        }
    }
    if (!animalExiste) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: El código de animal ingresado no existe.", "Animal no encontrado", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 5. Validar capacidad máxima de la matriz de solicitudes (100)
    if (logica.GestorDatos.contadorSolicitudes >= 100) {
        javax.swing.JOptionPane.showMessageDialog(this, "Se ha alcanzado la capacidad máxima de solicitudes permitida (100).", "Capacidad llena", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 6. Guardar los datos en la matriz estática
    int index = logica.GestorDatos.contadorSolicitudes;
    logica.GestorDatos.solicitudes[index][0] = codSolicitud;
    logica.GestorDatos.solicitudes[index][1] = codAdoptante;
    logica.GestorDatos.solicitudes[index][2] = codAnimal;

    // 7. Incrementar contador
    logica.GestorDatos.contadorSolicitudes++;

    // Mensaje de éxito
    javax.swing.JOptionPane.showMessageDialog(this, "¡Solicitud de adopción registrada con éxito!");

    // 8. Limpiar campos
    jTtxtCodigo.setText("");
    jTtxtCodigoAdoptante.setText("");
    jTtxtCodigoAnimal.setText("");
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegresarActionPerformed
    VentanaPrincipal menuPrincipal = new VentanaPrincipal();
    menuPrincipal.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jBRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SolicitudAdopcion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTtxtCodigo;
    private javax.swing.JTextField jTtxtCodigoAdoptante;
    private javax.swing.JTextField jTtxtCodigoAnimal;
    // End of variables declaration//GEN-END:variables
}
