/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author vicky
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBAnimales = new javax.swing.JButton();
        jBAdoptantes = new javax.swing.JButton();
        jBSolicitudes = new javax.swing.JButton();
        jBRescates = new javax.swing.JButton();
        jBReportes = new javax.swing.JButton();
        jBEspacios = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 153));
        jLabel1.setText("Menú Rescate Animal");
        jLabel1.setToolTipText("");

        jBAnimales.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jBAnimales.setText("Gestión de Animales");
        jBAnimales.addActionListener(this::jBAnimalesActionPerformed);

        jBAdoptantes.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jBAdoptantes.setText("Gestión de Adoptantes.");
        jBAdoptantes.addActionListener(this::jBAdoptantesActionPerformed);

        jBSolicitudes.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jBSolicitudes.setText("Gestión de Solicitudes de Adopción.");
        jBSolicitudes.addActionListener(this::jBSolicitudesActionPerformed);

        jBRescates.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jBRescates.setText("Gestión de Rescates.");
        jBRescates.addActionListener(this::jBRescatesActionPerformed);

        jBReportes.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jBReportes.setText("Reportes y Bitácoras.");
        jBReportes.addActionListener(this::jBReportesActionPerformed);

        jBEspacios.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jBEspacios.setText("Espacios de Refugio");
        jBEspacios.addActionListener(this::jBEspaciosActionPerformed);

        jButton7.setBackground(new java.awt.Color(255, 0, 153));
        jButton7.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Salir.");
        jButton7.addActionListener(this::jButton7ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBEspacios, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jBSolicitudes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBAdoptantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBAnimales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBRescates, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addComponent(jLabel1)))
                            .addComponent(jBReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(jBAnimales)
                .addGap(27, 27, 27)
                .addComponent(jBAdoptantes)
                .addGap(18, 18, 18)
                .addComponent(jBSolicitudes)
                .addGap(18, 18, 18)
                .addComponent(jBRescates)
                .addGap(24, 24, 24)
                .addComponent(jBEspacios)
                .addGap(18, 18, 18)
                .addComponent(jBReportes)
                .addGap(40, 40, 40)
                .addComponent(jButton7)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAdoptantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdoptantesActionPerformed
        RegistrarAdoptante ventana = new RegistrarAdoptante();
        ventana.setVisible(true);
    }//GEN-LAST:event_jBAdoptantesActionPerformed

    private void jBRescatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRescatesActionPerformed
        RegistrarRescate ventanaRescate = new RegistrarRescate();
    ventanaRescate.setVisible(true);
    this.dispose(); // Cierra el menú principal
    }//GEN-LAST:event_jBRescatesActionPerformed

    private void jBReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReportesActionPerformed
       javax.swing.JOptionPane.showMessageDialog(this, "Módulo de Reportes HTML y Bitácoras en desarrollo.");
    }//GEN-LAST:event_jBReportesActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       int opcion = javax.swing.JOptionPane.showConfirmDialog(this, "¿Estás segura de que deseas cerrar sesión?", "Confirmar salida", javax.swing.JOptionPane.YES_NO_OPTION);
    if (opcion == javax.swing.JOptionPane.YES_OPTION) {
        // Te regresa al Login
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jBEspaciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEspaciosActionPerformed
        RegistrarEspacio ventanaEspacio = new RegistrarEspacio();
    ventanaEspacio.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jBEspaciosActionPerformed

    private void jBAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAnimalesActionPerformed
        Registrar ventanaRegistro = new Registrar();
    ventanaRegistro.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jBAnimalesActionPerformed

    private void jBSolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSolicitudesActionPerformed
        SolicitudAdopcion ventanaSolicitud = new SolicitudAdopcion();
    ventanaSolicitud.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jBSolicitudesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdoptantes;
    private javax.swing.JButton jBAnimales;
    private javax.swing.JButton jBEspacios;
    private javax.swing.JButton jBReportes;
    private javax.swing.JButton jBRescates;
    private javax.swing.JButton jBSolicitudes;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
