/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author vicky
 */
public class VentanaReportes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaReportes.class.getName());

    /**
     * Creates new form VentanaReportes
     */
    public VentanaReportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaReportes = new javax.swing.JTextArea();
        jBBitacora = new javax.swing.JButton();
        jBRegresar = new javax.swing.JButton();
        jBRefugio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 153));
        jLabel1.setText("Reportes y Bitácoras del Sistema");

        txtAreaReportes.setColumns(20);
        txtAreaReportes.setFont(new java.awt.Font("Modern No. 20", 0, 12)); // NOI18N
        txtAreaReportes.setRows(5);
        jScrollPane1.setViewportView(txtAreaReportes);

        jBBitacora.setBackground(new java.awt.Color(255, 0, 153));
        jBBitacora.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jBBitacora.setForeground(new java.awt.Color(255, 255, 255));
        jBBitacora.setText("Generar Bitácora");
        jBBitacora.addActionListener(this::jBBitacoraActionPerformed);

        jBRegresar.setBackground(new java.awt.Color(255, 0, 153));
        jBRegresar.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jBRegresar.setForeground(new java.awt.Color(255, 255, 255));
        jBRegresar.setText("Regresar");
        jBRegresar.addActionListener(this::jBRegresarActionPerformed);

        jBRefugio.setBackground(new java.awt.Color(255, 0, 153));
        jBRefugio.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jBRefugio.setForeground(new java.awt.Color(255, 255, 255));
        jBRefugio.setText("Generar Reporte de Refugios");
        jBRefugio.addActionListener(this::jBRefugioActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBRefugio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBBitacora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(119, 119, 119))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jBBitacora)
                .addGap(18, 18, 18)
                .addComponent(jBRefugio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBRegresar)
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBitacoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBitacoraActionPerformed
    txtAreaReportes.setText(""); // Limpia el área de texto antes de escribir
    txtAreaReportes.append("=== BITÁCORA DEL SISTEMA - RESCATE ANIMAL ===\n");
    txtAreaReportes.append("• Se inicializó el módulo de Espacio de Refugio.\n");
    try {
        // Intentamos leer el archivo de la bitácora directamente
        java.io.File archivo = new java.io.File("bitacora_acciones.txt");
        
        if (archivo.exists()) {
            java.util.Scanner lector = new java.util.Scanner(archivo);
            int contadorAcciones = 0;
            
            while (lector.hasNextLine()) {
                String linea = lector.nextLine();
                txtAreaReportes.append("• " + linea + "\n");
                contadorAcciones++;
            }
            lector.close();
            
            txtAreaReportes.append("\n----------------------------------------\n");
            txtAreaReportes.append("Total de registros en la bitácora: " + contadorAcciones + "\n");
        } else {
            txtAreaReportes.append("Aviso: No se encontró el archivo 'bitacora_acciones.txt' en la ruta del proyecto.\n");
            txtAreaReportes.append("Asegúrate de realizar alguna acción para que se genere el archivo.\n");
        }
    } catch (Exception e) {
        txtAreaReportes.append("Error al leer la bitácora: " + e.getMessage() + "\n");
    }
    }//GEN-LAST:event_jBBitacoraActionPerformed

    private void jBRefugioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRefugioActionPerformed
    txtAreaReportes.setText(""); // Limpia el área de texto antes de mostrar
    txtAreaReportes.append("=== REPORTE DE ESPACIOS DE REFUGIO ===\n\n");
    
    try {
        // Usamos la ruta absoluta exacta de tu computadora
        java.io.File archivo = new java.io.File("C:\\Users\\vicky\\OneDrive\\Documentos\\NetBeansProjects\\PROYECTO_1\\refugios.txt");
        
        if (archivo.exists()) {
            java.util.Scanner lector = new java.util.Scanner(archivo);
            int contadorRefugios = 0;
            
            while (lector.hasNextLine()) {
                String linea = lector.nextLine();
                txtAreaReportes.append("• " + linea + "\n");
                contadorRefugios++;
            }
            lector.close();
            
            txtAreaReportes.append("\n----------------------------------------\n");
            txtAreaReportes.append("Total de refugios registrados: " + contadorRefugios + "\n");
        } else {
            txtAreaReportes.append("Aviso: No se encontró el archivo 'refugios.txt'.\n");
            txtAreaReportes.append("Registra algunos refugios en el sistema para que aparezcan aquí.\n");
        }
    } catch (Exception e) {
        txtAreaReportes.append("Error al leer el reporte de refugios: " + e.getMessage() + "\n");
    }
    }//GEN-LAST:event_jBRefugioActionPerformed

    private void jBRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaReportes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBitacora;
    private javax.swing.JButton jBRefugio;
    private javax.swing.JButton jBRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaReportes;
    // End of variables declaration//GEN-END:variables
}
